In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/City_Subset_with_TimeSeries.csv")
society_lat_long = pd.read_csv("../data/societies_latlong.csv")
# society_lat_long.head()
society_lat_long = society_lat_long.set_index("society_id")
# df["lat"] = df.society_id.apply(lambda x: society_lat_long["lat"][x])
# df["long"] = df.society_id.apply(lambda x: society_lat_long["long"][x])
df["area"] = df.society_id.apply(lambda x: society_lat_long["area"][x])

df.order_date = pd.to_datetime(df.order_date,format='%Y-%m-%d') 

number_of_weeks = max(df.order_week)
number_of_months = max(df.order_month)
date_range = int(str(max(df.order_date) - min(df.order_date)).split(" ")[0])
df["week_of_month"] = df.order_day.apply(lambda x: np.ceil(x/7))
df.head()

,customer_id,manufacturer_id,society_id,city_id,route_id,store_id,order_id,order_date,category_id,subcategory_id,...,order_placed_day,order_placed_month,order_placed_day_of_week,order_placed_hour,order_day,order_week,order_month,order_day_of_week,area,week_of_month
0,20049456,1148224,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122464,1124816,...,26,1,5,12,27,4,1,6,0,4.0
1,20164592,1122016,1256416,1120784,1137248,1120112,734763008,2019-01-27,1122576,1125152,...,26,1,5,20,27,4,1,6,0,4.0
2,20049456,1155504,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,26,1,5,13,27,4,1,6,0,4.0
3,20049456,1127728,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126160,...,26,1,5,13,27,4,1,6,0,4.0
4,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,26,1,5,20,27,4,1,6,0,4.0

In [53]:
prod = pd.DataFrame(df.product_id.unique(),columns=["product_id"])
prod.to_csv("product_ids.csv",index=None)

In [3]:
df.columns

Index(['customer_id', 'manufacturer_id', 'society_id', 'city_id', 'route_id',
       'store_id', 'order_id', 'order_date', 'category_id', 'subcategory_id',
       'product_id', 'product_quantity', 'selling_price_per_unit',
       'total_cost', 'subscription', 'product_addedtobasket_on',
       'order_placed_date', 'order_placed_day', 'order_placed_month',
       'order_placed_day_of_week', 'order_placed_hour', 'order_day',
       'order_week', 'order_month', 'order_day_of_week', 'lat', 'long', 'area',
       'week_of_month'],
      dtype='object')

In [6]:
df.groupby("area").count()

,customer_id,manufacturer_id,society_id,city_id,route_id,store_id,order_id,order_date,category_id,subcategory_id,...,order_placed_month,order_placed_day_of_week,order_placed_hour,order_day,order_week,order_month,order_day_of_week,lat,long,week_of_month
area,,,,,,,,,,,,,,,,,,,,,
0,29143,29143,29143,29143,29143,29143,29143,29143,29143,29143,...,29143,29143,29143,29143,29143,29143,29143,29143,29143,29143
1,21396,21396,21396,21396,21396,21396,21396,21396,21396,21396,...,21396,21396,21396,21396,21396,21396,21396,21396,21396,21396
2,22857,22857,22857,22857,22857,22857,22857,22857,22857,22857,...,22857,22857,22857,22857,22857,22857,22857,22857,22857,22857
3,16519,16519,16519,16519,16519,16519,16519,16519,16519,16519,...,16519,16519,16519,16519,16519,16519,16519,16519,16519,16519
4,12291,12291,12291,12291,12291,12291,12291,12291,12291,12291,...,12291,12291,12291,12291,12291,12291,12291,12291,12291,12291
5,28308,28308,28308,28308,28308,28308,28308,28308,28308,28308,...,28308,28308,28308,28308,28308,28308,28308,28308,28308,28308
6,24002,24002,24002,24002,24002,24002,24002,24002,24002,24002,...,24002,24002,24002,24002,24002,24002,24002,24002,24002,24002
7,15789,15789,15789,15789,15789,15789,15789,15789,15789,15789,...,15789,15789,15789,15789,15789,15789,15789,15789,15789,15789
8,18513,18513,18513,18513,18513,18513,18513,18513,18513,18513,...,18513,18513,18513,18513,18513,18513,18513,18513,18513,18513
9,15935,15935,15935,15935,15935,15935,15935,15935,15935,15935,...,15935,15935,15935,15935,15935,15935,15935,15935,15935,15935
10,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,...,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689
11,13488,13488,13488,13488,13488,13488,13488,13488,13488,13488,...,13488,13488,13488,13488,13488,13488,13488,13488,13488,13488
12,9869,9869,9869,9869,9869,9869,9869,9869,9869,9869,...,9869,9869,9869,9869,9869,9869,9869,9869,9869,9869
13,2076,2076,2076,2076,2076,2076,2076,2076,2076,2076,...,2076,2076,2076,2076,2076,2076,2076,2076,2076,2076

In [5]:
customer_q = pd.read_csv("../output/customer_intermediate.csv")
# area_q.set_index("area")
customer_q

,customer_id,mean_daily_cost,mean_order_cost,mean_weekly_cost,society_id,CUM_VAR,quintile
0,33023200,0.660486,122.190000,3.941613,1269408,0.000010,1.0
1,25203136,0.838757,155.170000,5.005484,1273104,0.000022,1.0
2,3422832,5.332162,54.802778,31.820968,1338400,0.000102,1.0
3,10176208,10.257297,126.506667,61.212903,1294944,0.000254,1.0
4,8242304,12.676108,71.063030,75.647742,1280944,0.000443,1.0
5,23591232,13.782426,169.983260,82.249965,1282512,0.000648,1.0
6,7752304,13.895027,151.210588,82.921935,1282176,0.000855,1.0
7,13492864,14.839297,183.018000,88.557097,1333024,0.001076,1.0
8,36351168,16.502222,381.613887,98.481003,1282624,0.001321,1.0
9,23895984,16.599676,127.955833,99.062581,1285312,0.001568,1.0
10,23806496,17.768865,131.489600,106.040000,1294048,0.001833,1.0
11,28454384,17.891879,91.944381,106.774119,1258096,0.002099,1.0
12,15182720,18.473946,79.480930,110.247742,1266048,0.002374,1.0
13,20778576,19.645622,151.435000,117.240000,1256416,0.002666,1.0
14,21401968,21.357459,77.473137,127.455806,1272544,0.002984,1.0
15,21792400,21.603027,190.312381,128.921290,1284976,0.003306,1.0
16,25650352,22.198824,62.223977,132.476855,1337504,0.003636,1.0
17,28120624,26.826865,57.708953,160.095806,1259440,0.004035,1.0
18,23166080,28.473929,94.065658,169.925060,1272096,0.004459,1.0
19,6878816,29.933522,113.014318,178.635535,1289232,0.004905,1.0
20,34845552,31.066882,87.081412,185.399135,1334704,0.005367,1.0
21,7491344,31.140108,137.164762,185.836129,1256416,0.005831,1.0
22,32159456,32.483514,63.257368,193.853226,1339744,0.006314,1.0
23,33408032,32.491967,176.794524,193.903671,1338064,0.006798,1.0
24,24441872,32.749534,77.675177,195.440767,1260112,0.007285,1.0
25,33583760,32.785497,73.967279,195.655384,1289344,0.007773,1.0
26,30956128,33.680097,59.911711,200.994126,1293936,0.008274,1.0
27,29661072,34.298106,91.958690,204.682246,1331792,0.008785,1.0
28,35171696,34.635041,68.897661,206.692984,1267840,0.009300,1.0
29,31300640,34.920891,81.776771,208.398867,1289344,0.009820,1.0
...,...,...,...,...,...,...,...
831,27650896,148.003635,322.125559,883.247500,1282064,0.929409,5.0
832,41704656,148.366324,428.871406,885.411935,1289792,0.931617,5.0
833,29695344,149.268865,220.917920,890.798065,1263472,0.933838,5.0
834,26472320,149.911505,195.307243,894.633177,1281840,0.936069,5.0
835,24248000,150.012799,183.790515,895.237671,1286544,0.938302,5.0
836,26410496,150.097754,269.593053,895.744661,1286432,0.940536,5.0
837,21877744,150.394575,191.882734,897.516013,1296624,0.942774,5.0
838,20514256,150.783379,242.564567,899.836297,1260784,0.945018,5.0
839,26825008,150.922732,300.222639,900.667916,1260784,0.947264,5.0
840,29272544,151.222923,354.129630,902.459381,1293824,0.949515,5.0
841,26035408,151.433886,282.982514,903.718352,1281840,0.951769,5.0
842,31972080,152.024326,262.845798,907.241948,1292368,0.954031,5.0
843,20298656,152.564292,340.052941,910.464325,1259552,0.956302,5.0
844,20541024,153.385162,515.931909,915.363065,1272992,0.958585,5.0
845,34309408,153.883054,281.865000,918.334355,1281168,0.960875,5.0
846,30754416,157.386324,231.083095,939.240968,1331792,0.963217,5.0
847,26418000,157.702865,339.244535,941.130000,1281504,0.965564,5.0
848,27676096,162.715044,358.360514,971.041394,1291584,0.967986,5.0
849,27456800,164.000293,221.460249,978.711424,1284752,0.970427,5.0
850,31844064,168.614212,271.248949,1006.246103,1260560,0.972936,5.0
851,21727776,171.746676,219.125069,1024.939839,1267168,0.975492,5.0
852,25883872,173.442067,265.180020,1035.057499,1338960,0.978073,5.0
853,26034960,173.797081,226.425775,1037.176129,1339632,0.980660,5.0
854,23711184,175.013784,204.921203,1044.437097,1290016,0.983265,5.0
855,35839104,175.785849,318.827275,1049.044582,1272880,0.985881,5.0
856,28046592,176.155081,245.027744,1051.248065,1335040,0.988503,5.0
857,25895184,178.037503,222.546878,1062.481871,1263696,0.991152,5.0
858,29650880,178.264041,458.039550,1063.833793,1289792,0.993805,5.0
859,30372720,184.223759,921.118795,1099.399852,1333248,0.996547,5.0
860,20608112,232.008390,703.632003,1384.566200,1271984,1.000000,5.0

1150128

In [44]:

# areas = df.area.unique()
customer_data = []
for customer in customer_q.customer_id:
    customer_insights = {}
    customer_df = df.loc[df.customer_id == customer]
    customer_insights["customer_id"] = customer
    customer_insights["num_products"] = len(customer_df.product_id.unique())
    if customer_df.subscription.any()==1:
        customer_insights["subscription"]  = 1
    else:
        customer_insights["subscription"]  = 0
#     customer_insights["num_societies"] = len(area_df.society_id.unique())
    customer_insights["quintile"] = customer_q.loc[customer_q.customer_id == customer].quintile.reset_index()["quintile"][0]
    customer_insights["top_5_products"] = [i for i in customer_df.groupby(["product_id"]).sum().sort_values("product_quantity",ascending=False).index[:5].values]
#     customer_insights["top_5_brands"] = [i for i in customer_df.groupby(["manufacturer_id"]).sum().sort_values("product_quantity",ascending=False).index[:5].values]
    consolidated = customer_df.groupby("order_id")
    customer_insights["mean_order_cost"] = consolidated.total_cost.sum().mean()
    customer_insights["favourite_brand"] = customer_df.manufacturer_id.mode().values[0]
    customer_insights["product_category"] = customer_df.category_id.mode().values[0]
    customer_insights["frequent_hour_slot"] = customer_df.order_placed_hour.mode().values[0]
    
    customer_insights["avg_spend_per_day"] = (customer_df.groupby("order_date").total_cost.sum().sum())/date_range
    customer_insights["avg_order_per_day"] = (customer_df.groupby("order_date").order_id.count().sum())/date_range
#     customer_insights["buying_pattern"] = [i  for i in customer_df[customer_df.index.values[-5:]]]
#     customer_insights["day_of_week_graph"] = [i/number_of_weeks for i in customer_df.groupby("order_day_of_week")["total_cost"].sum()]
#     customer_insights["week_of_month_graph"] = [i/number_of_months for i in customer_df.groupby("week_of_month")["total_cost"].sum()]

    
    customer_data.append(customer_insights)
customer_insights = pd.DataFrame([a for a in customer_data])

In [45]:
customer_df.index.values[-5:]

array([158428, 158474, 158633, 158827, 158955], dtype=int64)

In [46]:
customer_insights

,avg_order_per_day,avg_spend_per_day,customer_id,favourite_brand,frequent_hour_slot,mean_order_cost,num_products,product_category,quintile,subscription,top_5_products
0,0.010811,0.660486,33023200,1122016,20,122.190000,2,1122576,1.0,0,"[1120224, 2026640]"
1,0.010811,0.838757,25203136,1150128,17,155.170000,2,1124592,1.0,0,"[2499168, 3424176]"
2,0.113514,5.332162,3422832,1150128,1,54.802778,8,1123472,1.0,1,"[1670032, 1120224, 1927632, 2080176, 1572368]"
3,0.232432,10.257297,10176208,1122016,21,126.506667,20,1122576,1.0,1,"[1120224, 1984864, 2165968, 2310784, 1688064]"
4,0.237838,12.676108,8242304,1122016,1,71.063030,13,1122576,1.0,1,"[1698256, 2515184, 1684256, 1687504, 1688064]"
5,0.205405,13.782426,23591232,1134336,22,169.983260,21,1122576,1.0,0,"[1707888, 2026640, 1609328, 1693328, 1120224]"
6,0.259459,13.895027,7752304,1122016,21,151.210588,28,1122576,1.0,1,"[1120112, 1673952, 2335424, 2955232, 1729056]"
7,0.270270,14.839297,13492864,1126048,19,183.018000,41,1122464,1.0,0,"[2310784, 2199904, 1676080, 1650992, 2408000]"
8,0.421622,16.502222,36351168,1150128,19,381.613888,52,1123472,1.0,1,"[1707888, 2118368, 2119488, 1647968, 1688064]"
9,0.470270,16.599676,23895984,1134336,22,127.955833,42,1122576,1.0,0,"[1120560, 2507120, 2432080, 1121120, 1915760]"
10,0.335135,17.768865,23806496,1150128,23,131.489600,45,1122576,1.0,0,"[1707888, 1970640, 1901984, 1124144, 2026640]"
11,0.454054,17.891879,28454384,1150128,22,91.944381,39,1123472,1.0,1,"[1670032, 2165968, 1120224, 2842336, 1132992]"
12,0.308108,18.473946,15182720,1134336,1,79.480930,18,1122576,1.0,1,"[1120448, 1120112, 2507120, 1120560, 3621632]"
13,0.654054,19.645622,20778576,1150128,21,151.435000,44,1123472,1.0,0,"[1120112, 2166080, 1668240, 1902656, 1688064]"
14,0.729730,21.357459,21401968,1134336,1,77.473137,55,1122576,1.0,1,"[2507120, 1939280, 1670032, 1931776, 1994384]"
15,0.389189,21.603027,21792400,1150128,20,190.312381,34,1122576,1.0,0,"[1120672, 2335424, 1708336, 2080176, 1687280]"
16,1.151351,22.198824,25650352,1122016,23,61.295261,52,1122576,1.0,0,"[1120224, 2507120, 2714880, 2310784, 1422960]"
17,1.097297,26.826865,28120624,1122016,22,57.708953,57,1122576,1.0,0,"[2166080, 2026640, 3816960, 1681904, 1688064]"
18,1.037838,28.473929,23166080,1134336,21,94.065658,47,1122576,1.0,0,"[1707888, 1120448, 1120896, 1939280, 1709008]"
19,1.097297,29.933522,6878816,1150128,19,113.014318,42,1123472,1.0,1,"[2718016, 3816960, 1902208, 2165968, 1120784]"
20,1.216216,31.066882,34845552,1122016,19,87.081412,60,1122576,1.0,0,"[1120336, 2166080, 1698256, 1681904, 1125600]"
21,0.475676,31.140108,7491344,1122016,1,137.164762,31,1122576,1.0,1,"[1120336, 1382640, 1379840, 2691696, 3912944]"
22,1.356757,32.483514,32159456,1134336,1,63.257368,39,1122576,1.0,1,"[1120448, 1707888, 2515184, 2714880, 2502864]"
23,1.108108,32.491967,33408032,1150128,20,176.794524,64,1123472,1.0,0,"[1120224, 2118368, 1120336, 1683808, 1681904]"
24,1.118919,32.749534,24441872,1150128,23,77.675177,56,1123472,1.0,1,"[1120112, 1694896, 1902656, 1670032, 1709008]"
25,1.113514,32.785497,33583760,1134336,14,73.967279,74,1122576,1.0,1,"[1120560, 1120672, 1125600, 1688064, 1681904]"
26,1.254054,33.680097,30956128,1150128,20,59.911711,38,1123472,1.0,1,"[1120336, 1120224, 1683696, 1694000, 1688064]"
27,1.210811,34.298106,29661072,1150128,23,91.958690,92,1123472,1.0,0,"[1681904, 1120224, 1684816, 2119152, 1694336]"
28,1.416216,34.635041,35171696,1122016,20,68.897661,68,1122576,1.0,1,"[1120224, 2166080, 1984864, 1120336, 1681904]"
29,1.162162,34.920891,31300640,1150128,19,81.776771,57,1123472,1.0,1,"[1120672, 1681904, 1688064, 1684816, 1709008]"
...,...,...,...,...,...,...,...,...,...,...,...
831,2.772973,148.003635,27650896,1150128,22,322.125559,211,1123472,5.0,0,"[1707888, 1670032, 1645728, 1939280, 1687504]"
832,1.486486,148.366324,41704656,1150128,23,428.871406,102,1123472,5.0,1,"[1120224, 1120560, 1984864, 2041760, 2430848]"
833,1.913514,149.268865,29695344,1134336,23,220.917920,130,1122576,5.0,1,"[1120560, 1648752, 1725136, 1120224, 1984864]"
834,2.659459,149.911505,26472320,1150128,1,193.941458,129,1123472,5.0,1,"[1670032, 1120112, 1688064, 1681344, 1683696]"
835,2.367568,150.012799,24248000,1134336,23,183.790515,154,1122576,5.0,1,"[1120448, 1688064, 1939280, 1553888, 1681904]"
836,2.643243,150.097754,26410496,1150128,23,269.593053,276,1122576,5.0,0,"[1120560, 1707888, 1668240, 1125040, 1666784]"
837,2.221622,150.394575,21877744,1122016,1,191.882734,62,1122576,5.0,1,"[1120112, 2335424, 1688064, 1125376, 2718016]"
838,2.535135,150.783379,20514256,1122016,19,242.564567,106,1122576,5.0,1,"[1120336, 1984864, 1120224, 2515184, 1121008]"
839,2.691892,150.922732,26825008,1150128,11,300.222639,179,1123472,5.0,0,"[1553328, 1984864, 1901984, 1120224, 1688064]"
840,2.508108,151.222923,29272544,1150128,23,354.129630,158,1122576,5.0,1,"[2026640, 1414672, 1653456, 1645728, 1901872]"
841,2.443243,151.433886,26035408,1150128,21,282.982514,177,1123472,5.0,0,"[1120112, 1698256, 1423968, 1687392, 1688064]"
842,2.102703,152.024326,31972080,1122016,21,262.845798,71,1122576,5.0,1,"[1120224, 1120112, 2499168, 1688064, 1709008]"
843,2.340541,152.564292,20298656,1150128,19,340.052941,151,1123472,5.0,0,"[1688064, 1688960, 1709008, 1915760, 1687392]"
844,1.610811,153.385162,20541024,1150128,11,515.931909,153,1123472,5.0,0,"[1352400, 2045568, 1415344, 1647632, 1666784]"
845,1.491892,153.883054,34309408,1150128,1,281.865000,44,1123472,5.0,1,"[1670032, 2335424, 1698256, 2515184, 1125040]"
846,1.621622,157.386324,30754416,1134336,1,231.083095,54,1122576,5.0,1,"[1707888, 1670032, 1554000, 2515408, 2320304]"
847,2.270270,157.702865,26418000,1150128,22,339.244535,163,1122576,5.0,1,"[1120560, 1698256, 1627472, 1120896, 1683808]"
848,2.535135,162.715044,27676096,1122016,22,354.144508,204,1122576,5.0,1,"[1120224, 1120112, 1645728, 1120560, 2515184]"
849,2.659459,164.000293,27456800,1150128,1,221.460249,159,1123472,5.0,1,"[1698256, 1688064, 1688960, 1553664, 1686160]"
850,2.508108,168.614212,31844064,1122016,1,271.248949,126,1122576,5.0,1,"[1120224, 1120112, 1902656, 2514736, 1688064]"
851,2.751351,171.746676,21727776,1122016,1,219.125069,100,1122576,5.0,1,"[2026640, 1120224, 1645728, 1415344, 2515184]"
852,2.724324,173.442067,25883872,1150128,1,265.180020,187,1123472,5.0,1,"[2335424, 1688064, 1627472, 2714880, 1609328]"
853,2.621622,173.797081,26034960,1122016,1,226.425775,64,1122576,5.0,1,"[1120224, 1120112, 1120784, 2468816, 1984864]"
854,1.475676,175.013784,23711184,1122016,1,204.921203,57,1122576,5.0,1,"[2335424, 1120112, 2333408, 1645728, 2515184]"
855,2.351351,175.785849,35839104,1122016,12,318.827275,164,1122576,5.0,1,"[2026640, 2181760, 1861552, 1379840, 1120224]"
856,2.032432,176.155081,28046592,1122016,1,245.027744,28,1122576,5.0,1,"[1120336, 2335424, 2468816, 1120224, 1120448]"
857,2.621622,178.037503,25895184,1134336,1,222.546878,166,1122576,5.0,1,"[1120560, 1120224, 2718016, 2842224, 2333968]"
858,2.016216,178.264041,29650880,1150128,20,458.039550,147,1123472,5.0,1,"[1670032, 1120224, 2374400, 1684256, 1688064]"
859,2.556757,184.223759,30372720,1150128,22,921.118795,193,1123472,5.0,0,"[1670032, 1645728, 1120784, 1688064, 1379840]"
860,2.481081,232.008390,20608112,1150128,22,703.632003,242,1123472,5.0,0,"[1121344, 2310784, 2378544, 1124256, 1688064]"

In [47]:
customer_insights.to_csv("../output/customer_insights.csv",index=None)