In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/City_Subset_with_TimeSeries.csv")
society_lat_long = pd.read_csv("../data/societies_latlong.csv")
# society_lat_long.head()
society_lat_long = society_lat_long.set_index("society_id")
df["lat"] = df.society_id.apply(lambda x: society_lat_long["lat"][x])
df["long"] = df.society_id.apply(lambda x: society_lat_long["long"][x])
df["area"] = df.society_id.apply(lambda x: society_lat_long["area"][x])

df.order_date = pd.to_datetime(df.order_date,format='%Y-%m-%d') 

number_of_weeks = max(df.order_week)
number_of_months = max(df.order_month)
date_range = int(str(max(df.order_date) - min(df.order_date)).split(" ")[0])
df["week_of_month"] = df.order_day.apply(lambda x: np.ceil(x/7))
df.head()

,customer_id,manufacturer_id,society_id,city_id,route_id,store_id,order_id,order_date,category_id,subcategory_id,...,order_placed_day_of_week,order_placed_hour,order_day,order_week,order_month,order_day_of_week,lat,long,area,week_of_month
0,20049456,1148224,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122464,1124816,...,5,12,27,4,1,6,18.485728,73.802289,0,4.0
1,20164592,1122016,1256416,1120784,1137248,1120112,734763008,2019-01-27,1122576,1125152,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
2,20049456,1155504,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
3,20049456,1127728,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126160,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
4,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0

In [3]:
df.columns

Index(['customer_id', 'manufacturer_id', 'society_id', 'city_id', 'route_id',
       'store_id', 'order_id', 'order_date', 'category_id', 'subcategory_id',
       'product_id', 'product_quantity', 'selling_price_per_unit',
       'total_cost', 'subscription', 'product_addedtobasket_on',
       'order_placed_date', 'order_placed_day', 'order_placed_month',
       'order_placed_day_of_week', 'order_placed_hour', 'order_day',
       'order_week', 'order_month', 'order_day_of_week', 'lat', 'long', 'area',
       'week_of_month'],
      dtype='object')

In [4]:
Area_centers = [
  {
    "lat": 18.464815,
    "long": 73.796439
  },
  {
    "lat": 18.507762,
    "long": 73.798775
  },
  {
    "lat": 18.52517,
    "long": 73.779009
  },
  {
    "lat": 18.56792,
    "long": 73.770989
  },
  {
    "lat": 18.556043,
    "long": 73.812341
  },
  {
    "lat": 18.683466,
    "long": 73.731081
  },
  {
    "lat": 18.665461,
    "long": 73.808566
  },
  {
    "lat": 18.565205,
    "long": 73.911494
  },
  {
    "lat": 18.529224,
    "long": 73.860415
  },
  {
    "lat": 18.435227,
    "long": 73.889246
  },
  {
    "lat": 18.50861,
    "long": 73.934341
  },
  {
    "lat": 18.635565,
    "long": 73.843959
  },
  {
    "lat": 18.606168,
    "long": 73.874991
  },
  
  {
    "lat": 18.599301,
    "long": 73.927049
  },
  {
    "lat": 18.59913,
    "long": 73.737242
  }
]

In [5]:
df

,customer_id,manufacturer_id,society_id,city_id,route_id,store_id,order_id,order_date,category_id,subcategory_id,...,order_placed_day_of_week,order_placed_hour,order_day,order_week,order_month,order_day_of_week,lat,long,area,week_of_month
0,20049456,1148224,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122464,1124816,...,5,12,27,4,1,6,18.485728,73.802289,0,4.0
1,20164592,1122016,1256416,1120784,1137248,1120112,734763008,2019-01-27,1122576,1125152,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
2,20049456,1155504,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
3,20049456,1127728,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126160,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
4,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
5,20049456,1128624,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122912,1127392,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
6,20049456,1122016,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122576,1124928,...,5,12,27,4,1,6,18.485728,73.802289,0,4.0
7,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
8,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
9,20164592,1133888,1256416,1120784,1137248,1120112,734763008,2019-01-27,1122464,1124816,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
10,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1131312,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
11,20049456,1122016,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122576,1125376,...,5,12,27,4,1,6,18.485728,73.802289,0,4.0
12,20049456,1120784,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
13,20049456,1130528,1267056,1120784,1138032,1120112,734536432,2019-01-27,1123024,1127728,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
14,20049456,1150128,1267056,1120784,1138032,1120112,734536432,2019-01-27,1123472,1131312,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
15,20049456,1136688,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126160,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
16,20049456,1152816,1267056,1120784,1138032,1120112,734536432,2019-01-27,1123136,1128960,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
17,20049456,1159984,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
18,20049456,1128624,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122912,1127392,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
19,20049456,1120784,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
20,20164592,1123472,1256416,1120784,1137248,1120112,734763008,2019-01-27,1122688,1128512,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
21,20049456,1120784,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122800,1126496,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
22,20049456,1130528,1267056,1120784,1138032,1120112,734536432,2019-01-27,1123920,1126720,...,5,12,27,4,1,6,18.485728,73.802289,0,4.0
23,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
24,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
25,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
26,20164592,1150128,1256416,1120784,1137248,1120112,734763008,2019-01-27,1123472,1130640,...,5,20,27,4,1,6,18.469226,73.803260,0,4.0
27,20049456,1150128,1267056,1120784,1138032,1120112,734536432,2019-01-27,1123472,1131312,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
28,20049456,1122016,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122576,1124928,...,5,12,27,4,1,6,18.485728,73.802289,0,4.0
29,20049456,1152816,1267056,1120784,1138032,1120112,734536432,2019-01-27,1122688,1125488,...,5,13,27,4,1,6,18.485728,73.802289,0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250845,33040336,1122016,1262016,1120784,1137472,1120112,1672158096,2019-07-31,1122576,1125264,...,1,23,31,31,7,2,18.507865,73.861108,8,5.0
250846,24419584,1123248,1297296,1120784,1140720,1120112,1669735312,2019-07-31,1122688,1125488,...,1,22,31,31,7,2,18.601780,73.896891,12,5.0
250847,20160448,1134336,1256416,1120784,1137248,1120112,1666311248,2019-07-31,1122576,1125264,...,5,1,31,31,7,2,18.469226,73.803260,0,5.0
250848,36472240,1122688,1282512,1120784,1146208,1120112,1668608368,2019-07-31,1122688,1125488,...,1,20,31,31,7,2,18.447965,73.869249,9,5.0
250849,24793216,1134000,1262688,1120784,1137696,1120112,1667965152,2019-07-31,1125040,1141392,...,1,20,31,31,7,2,18.695358,73.714020,5,5.0
250850,29284864,1150128,1272096,1120784,1138592,1120112,1670899328,2019-07-31,1123472,1130640,...,1,15,31,31,7,2,18.468294,73.787233,0,5.0
250851,27123936,1134336,1332352,1120784,1146432,1120112,1672150144,2019-07-31,1122576,1125264,...,1,23,31,31,7,2,18.683449,73.796886,6,5.0
250852,40814816,1150128,1333024,1120784,1146432,1120112,1670155088,2019-07-31,1123472,1131312,...,6,23,31,31,7,2,18.550604,73.813397,4,5.0
250853,31651312,1122016,1281952,1120784,1146208,1120112,1666287840,2019-07-31,1122576,1125376,...,5,1,31,31,7,2,18.682136,73.797315,6,5.0
250854,28716128,1122016,1280944,1120784,1146320,1120112,1664941936,2019-07-31,1122576,1125264,...,5,1,31,31,7,2,18.522909,73.861474,8,5.0
250855,25734352,1153488,1279600,1120784,1138592,1120112,1671233312,2019-07-31,1122464,1131088,...,1,19,31,31,7,2,18.622746,73.863982,12,5.0
250856,20273120,1150128,1269968,1120784,1138368,1120112,1671067888,2019-07-31,1123472,1130640,...,1,17,31,31,7,2,18.539298,73.850549,8,5.0
250857,42054432,1150128,1339408,1120784,1146544,1120112,1666426944,2019-07-31,1123472,1130640,...,1,22,31,31,7,2,18.446327,73.868685,9,5.0
250858,35548016,1125488,1296064,1120784,1140720,1120112,1667297184,2019-07-31,1123136,1132320,...,1,11,31,31,7,2,18.573621,73.799388,4,5.0
250859,27198192,1150128,1333136,1120784,1146544,1120112,1671472432,2019-07-31,1123472,1130640,...,1,20,31,31,7,2,18.525432,73.841007,8,5.0
250860,35048720,1122016,1288112,1120784,1140272,1120112,1669872848,2019-07-31,1122576,1125264,...,4,1,31,31,7,2,18.529435,73.941769,10,5.0
250861,43706432,1122016,1270976,1120784,1138480,1120112,1668774240,2019-07-31,1122576,1125264,...,2,1,31,31,7,2,18.421984,73.896769,9,5.0
250862,37613968,1122016,1332800,1120784,1146432,1120112,1671442752,2019-07-31,1122576,1125264,...,1,20,31,31,7,2,18.559948,73.782791,3,5.0
250863,28602112,1125824,1338736,1120784,1146544,1120112,1670494784,2019-07-31,1122464,1124816,...,1,19,31,31,7,2,18.577586,73.764967,3,5.0
250864,22493072,1188768,1291584,1120784,1140384,1120112,1670691344,2019-07-31,1122912,1127280,...,1,12,31,31,7,2,18.630435,73.845116,11,5.0
250865,22205792,1150128,1264144,1120784,1137808,1120112,1669713920,2019-07-31,1123472,1130640,...,1,20,31,31,7,2,18.448410,73.781869,0,5.0
250866,28325696,1122016,1334704,1120784,1146432,1120112,1668520784,2019-07-31,1122576,1125264,...,2,1,31,31,7,2,18.512602,73.857374,8,5.0
250867,29318016,1122016,1335488,1120784,1146432,1120112,1668542176,2019-07-31,1122576,1125264,...,2,1,31,31,7,2,18.670340,73.797941,6,5.0
250868,6888224,1134336,1281168,1120784,1146320,1120112,1667770272,2019-07-31,1122576,1125376,...,1,21,31,31,7,2,18.594181,73.888402,12,5.0
250869,20460720,1122016,1270976,1120784,1138480,1120112,1671199376,2019-07-31,1122576,1125264,...,1,19,31,31,7,2,18.421984,73.896769,9,5.0
250870,35048720,1150128,1288112,1120784,1140272,1120112,1669872848,2019-07-31,1123472,1131312,...,1,22,31,31,7,2,18.529435,73.941769,10,5.0
250871,25960816,1140160,1285312,1120784,1140160,1120112,1671667312,2019-07-31,1122576,1125152,...,1,21,31,31,7,2,18.512722,73.924577,10,5.0
250872,37796976,1141952,1334032,1120784,1146432,1120112,1670742080,2019-07-31,1123472,1132992,...,1,22,31,31,7,2,18.602514,73.883877,12,5.0
250873,26019056,1130976,1285984,1120784,1140160,1120112,1669803632,2019-07-31,1123024,1128064,...,1,23,31,31,7,2,18.647511,73.841726,11,5.0
250874,26777184,1150128,1271872,1120784,1138480,1120112,1671152448,2019-07-31,1123472,1130640,...,1,18,31,31,7,2,18.680107,73.727521,5,5.0

In [6]:
df.groupby("area").count()

,customer_id,manufacturer_id,society_id,city_id,route_id,store_id,order_id,order_date,category_id,subcategory_id,...,order_placed_month,order_placed_day_of_week,order_placed_hour,order_day,order_week,order_month,order_day_of_week,lat,long,week_of_month
area,,,,,,,,,,,,,,,,,,,,,
0,29143,29143,29143,29143,29143,29143,29143,29143,29143,29143,...,29143,29143,29143,29143,29143,29143,29143,29143,29143,29143
1,21396,21396,21396,21396,21396,21396,21396,21396,21396,21396,...,21396,21396,21396,21396,21396,21396,21396,21396,21396,21396
2,22857,22857,22857,22857,22857,22857,22857,22857,22857,22857,...,22857,22857,22857,22857,22857,22857,22857,22857,22857,22857
3,16519,16519,16519,16519,16519,16519,16519,16519,16519,16519,...,16519,16519,16519,16519,16519,16519,16519,16519,16519,16519
4,12291,12291,12291,12291,12291,12291,12291,12291,12291,12291,...,12291,12291,12291,12291,12291,12291,12291,12291,12291,12291
5,28308,28308,28308,28308,28308,28308,28308,28308,28308,28308,...,28308,28308,28308,28308,28308,28308,28308,28308,28308,28308
6,24002,24002,24002,24002,24002,24002,24002,24002,24002,24002,...,24002,24002,24002,24002,24002,24002,24002,24002,24002,24002
7,15789,15789,15789,15789,15789,15789,15789,15789,15789,15789,...,15789,15789,15789,15789,15789,15789,15789,15789,15789,15789
8,18513,18513,18513,18513,18513,18513,18513,18513,18513,18513,...,18513,18513,18513,18513,18513,18513,18513,18513,18513,18513
9,15935,15935,15935,15935,15935,15935,15935,15935,15935,15935,...,15935,15935,15935,15935,15935,15935,15935,15935,15935,15935
10,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689,...,20689,20689,20689,20689,20689,20689,20689,20689,20689,20689
11,13488,13488,13488,13488,13488,13488,13488,13488,13488,13488,...,13488,13488,13488,13488,13488,13488,13488,13488,13488,13488
12,9869,9869,9869,9869,9869,9869,9869,9869,9869,9869,...,9869,9869,9869,9869,9869,9869,9869,9869,9869,9869
13,2076,2076,2076,2076,2076,2076,2076,2076,2076,2076,...,2076,2076,2076,2076,2076,2076,2076,2076,2076,2076

In [7]:
area_q = pd.read_csv("../output/area_intermediate.csv")
# area_q.set_index("area")
area_q

,area,mean_daily_cost,mean_order_cost,mean_weekly_cost,CUM_VAR,quintile
0,13,529.207441,959.837026,3158.173441,0.007876,1.0
1,12,2567.325078,2987.139241,15321.133529,0.046085,1.0
2,4,3394.295997,4186.298396,20256.282561,0.096601,1.0
3,11,3664.071299,3683.984730,21866.231947,0.151133,1.0
4,9,4298.796934,4467.850746,25654.110733,0.215111,2.0
5,3,4305.058227,5105.357513,25691.476518,0.279182,2.0
6,7,4308.714639,4581.104645,25713.297041,0.343307,2.0
7,8,4807.208103,4886.447797,28688.177391,0.414851,3.0
8,10,5400.816400,5489.840846,32230.678513,0.495230,3.0
9,1,5583.496802,5835.858239,33320.868010,0.578328,3.0
10,2,6169.102024,6484.567468,36815.608852,0.670141,4.0
11,6,6526.861397,6671.101428,38950.624467,0.767279,4.0
12,0,7499.654500,7499.654500,44756.002663,0.878894,5.0
13,5,8137.354096,8457.362404,48561.629285,1.000000,5.0

In [25]:
area_df["total_cost"] = area_df["product_quantity"] * area_df["selling_price_per_unit"]
area_df

In [8]:

# areas = df.area.unique()
area_data = []
for area in area_q.area:
    area_insights = {}
    area_df = df.loc[df.area == area]
    area_insights["area_id"] = area
    area_insights["num_users"] = len(area_df.customer_id.unique())
    area_insights["num_societies"] = len(area_df.society_id.unique())
    area_insights["quintile"] = area_q.loc[area_q.area == area].quintile.reset_index()["quintile"][0]
    area_insights["top_5_products"] = [i for i in area_df.groupby(["product_id"]).sum().sort_values("product_quantity",ascending=False).index[:5].values]
    area_insights["top_5_brands"] = [i for i in area_df.groupby(["manufacturer_id"]).sum().sort_values("product_quantity",ascending=False).index[:5].values]
    consolidated = area_df.groupby("order_id")
    area_insights["mean_order_cost"] = consolidated.total_cost.sum().mean()
    area_insights["avg_value_per_day"] = (area_df.groupby("order_date").total_cost.sum().sum())/date_range
    area_insights["avg_order_per_day"] = (area_df.groupby("order_date").order_id.count().sum())/date_range
    area_insights["number_of_warehouses"] = area_df.groupby(["area","store_id"]).count().shape[0]
    area_insights["day_of_week_graph"] = [i/number_of_weeks for i in area_df.groupby("order_day_of_week")["product_quantity"].sum()]
    area_insights["week_of_month_graph"] = [i/number_of_months for i in area_df.groupby("week_of_month")["product_quantity"].sum()]
    area_insights["lat"] = Area_centers[area]["lat"]
    area_insights["long"] = Area_centers[area]["long"]
    
    area_data.append(area_insights)
area_insights = pd.DataFrame([a for a in area_data])

In [9]:
area_insights

,area_id,avg_order_per_day,avg_value_per_day,day_of_week_graph,lat,long,mean_order_cost,num_societies,num_users,number_of_warehouses,quintile,top_5_brands,top_5_products,week_of_month_graph
0,13,11.221622,529.207441,"[15.870967741935484, 14.483870967741936, 13.16...",18.599301,73.927049,194.252731,7,7,1,1.0,"[1134336, 1122016, 1150128, 1123248, 1129072]","[1120448, 1984864, 1120672, 1120560, 1120224]","[98.42857142857143, 91.0, 82.57142857142857, 1..."
1,12,53.345946,2567.325078,"[66.61290322580645, 68.2258064516129, 70.51612...",18.606168,73.874991,172.209985,27,35,1,1.0,"[1134336, 1150128, 1122016, 1123248, 1129072]","[1707888, 1120672, 1670032, 1120560, 1939280]","[474.85714285714283, 443.57142857142856, 478.2..."
2,4,66.437838,3394.295997,"[103.87096774193549, 89.41935483870968, 88.193...",18.556043,73.812341,168.349801,15,46,1,1.0,"[1122016, 1150128, 1134336, 1123248, 1129184]","[2026640, 1707888, 1120224, 1120560, 1984864]","[588.2857142857143, 604.2857142857143, 604.714..."
3,11,72.908108,3664.071299,"[87.90322580645162, 93.03225806451613, 95.5161...",18.635565,73.843959,175.837403,24,39,1,1.0,"[1122016, 1150128, 1134336, 1123248, 1129184]","[1120224, 2026640, 1120560, 1120112, 1670032]","[609.4285714285714, 619.7142857142857, 633.714..."
4,9,86.135135,4298.796934,"[108.74193548387096, 117.90322580645162, 120.2...",18.435227,73.889246,178.433348,23,58,1,2.0,"[1122016, 1150128, 1134336, 1123248, 1124256]","[1120336, 1120560, 1984864, 1120112, 1120224]","[725.8571428571429, 782.4285714285714, 791.857..."
5,3,89.291892,4305.058227,"[116.35483870967742, 113.6774193548387, 119.67...",18.567920,73.770989,150.412799,18,65,1,2.0,"[1122016, 1134336, 1150128, 1123248, 1129072]","[1120224, 1707888, 1120560, 1120112, 1120448]","[807.2857142857143, 776.4285714285714, 773.285..."
6,7,85.345946,4308.714639,"[103.03225806451613, 115.0, 110.87096774193549...",18.565205,73.911494,157.969126,27,61,1,2.0,"[1122016, 1134336, 1150128, 1123248, 1134896]","[1120560, 1984864, 1120112, 1120224, 2026640]","[620.7142857142857, 760.8571428571429, 766.714..."
7,8,100.070270,4807.208103,"[135.29032258064515, 133.5483870967742, 136.32...",18.529224,73.860415,161.140333,22,65,1,3.0,"[1122016, 1150128, 1134336, 1123248, 1134896]","[2026640, 1120224, 1984864, 1707888, 1120112]","[829.1428571428571, 828.8571428571429, 887.0, ..."
8,10,111.832432,5400.816400,"[148.5483870967742, 139.19354838709677, 147.45...",18.508610,73.934341,173.133085,25,58,1,3.0,"[1122016, 1150128, 1134336, 1123248, 1129072]","[1120224, 2026640, 1120560, 1707888, 1120112]","[951.8571428571429, 990.8571428571429, 985.428..."
9,1,115.654054,5583.496802,"[158.67741935483872, 147.19354838709677, 155.3...",18.507762,73.798775,145.649592,26,75,1,3.0,"[1122016, 1150128, 1134336, 1123248, 1129072]","[1120224, 1120560, 1707888, 1120336, 1120112]","[1015.4285714285714, 998.1428571428571, 1111.8..."
10,2,123.551351,6169.102024,"[164.7741935483871, 160.61290322580646, 165.87...",18.525170,73.779009,167.319143,22,81,1,4.0,"[1122016, 1150128, 1134336, 1123248, 1123472]","[1120224, 1707888, 1120112, 1984864, 1120560]","[1076.7142857142858, 1134.0, 1150.285714285714..."
11,6,129.740541,6526.861397,"[173.61290322580646, 190.96774193548387, 179.8...",18.665461,73.808566,166.869729,27,84,1,4.0,"[1122016, 1134336, 1150128, 1123248, 1134896]","[1707888, 1120560, 1120224, 1120112, 1120672]","[1131.2857142857142, 1178.2857142857142, 1213...."
12,0,157.529730,7499.654500,"[210.2258064516129, 212.03225806451613, 210.48...",18.464815,73.796439,144.464398,24,103,1,5.0,"[1122016, 1150128, 1134336, 1123248, 1129072]","[1120224, 2026640, 1120560, 1707888, 1120112]","[1390.857142857143, 1481.5714285714287, 1481.2..."
13,5,153.016216,8137.354096,"[215.67741935483872, 214.09677419354838, 210.3...",18.683466,73.731081,172.322631,27,99,1,5.0,"[1122016, 1150128, 1134336, 1123248, 1134896]","[1120224, 2026640, 1120336, 1984864, 1670032]","[1375.857142857143, 1447.5714285714287, 1467.4..."

In [11]:
pods = pd.read_csv("../output/pod_data.csv")
# pods=pods.sort_values("area")
area_insights=area_insights.sort_values("area_id")
min_ = pods[['distance_from_ware_house','pod1','pod2','pod3']].min(axis=1)
pods["distance_from_ware_house"] = pods.distance_from_ware_house
pods["distance_from_pod_if_made"] = min_
pods["closest_pod_or_warehouse"] = pods[['distance_from_ware_house','pod1','pod2','pod3']].idxmin(axis=1)
pods.to_csv("pod_data.csv",header=None)
# min_

In [12]:
pods

,area,area_priority,lat,long,distance_from_ware_house,pod1,pod2,pod3,distance_from_pod_if_made,closest_pod_or_warehouse
0,0,2.666667,18.485728,73.802289,23.408588,0.000000,23.189913,20.658563,0.000000,pod1
1,2,2.636364,18.526163,73.795066,19.861086,4.540201,18.750943,16.377413,4.540201,pod1
2,5,2.629630,18.681886,73.725115,18.165195,23.189913,0.000000,10.928606,0.000000,pod2
3,6,2.481481,18.670743,73.828048,7.329557,20.658563,10.928606,0.000000,0.000000,pod3
4,3,2.388889,18.572750,73.778681,17.008054,9.949574,13.336953,12.032818,9.949574,pod1
5,1,2.269231,18.513894,73.795588,20.986450,3.196990,20.026890,17.695999,3.196990,pod1
6,4,2.266667,18.546868,73.819992,16.536195,7.020868,17.988744,13.737732,7.020868,pod1
7,8,2.181818,18.512602,73.857374,18.660788,6.533531,23.365526,17.775795,6.533531,pod1
8,10,1.960000,18.525055,73.923069,17.022023,13.476576,27.162630,18.989972,13.476576,pod1
9,9,1.913043,18.425186,73.875990,27.946355,10.271872,32.573152,27.647241,10.271872,pod1
10,7,1.629630,18.567508,73.917738,12.295152,15.183173,23.946928,14.837761,12.295152,distance_from_ware_house
11,11,1.500000,18.633523,73.847934,7.074805,17.053913,14.020210,4.623310,4.623310,pod3
12,12,1.074074,18.616141,73.876334,7.072477,16.415727,17.536427,7.904777,7.072477,distance_from_ware_house
13,13,1.000000,18.605777,73.920581,8.244049,18.235474,22.278536,12.126106,8.244049,distance_from_ware_house

In [13]:
area_insights

,area_id,avg_order_per_day,avg_value_per_day,day_of_week_graph,lat,long,mean_order_cost,num_societies,num_users,number_of_warehouses,quintile,top_5_brands,top_5_products,week_of_month_graph
12,0,157.529730,7499.654500,"[210.2258064516129, 212.03225806451613, 210.48...",18.464815,73.796439,144.464398,24,103,1,5.0,"[1122016, 1150128, 1134336, 1123248, 1129072]","[1120224, 2026640, 1120560, 1707888, 1120112]","[1390.857142857143, 1481.5714285714287, 1481.2..."
9,1,115.654054,5583.496802,"[158.67741935483872, 147.19354838709677, 155.3...",18.507762,73.798775,145.649592,26,75,1,3.0,"[1122016, 1150128, 1134336, 1123248, 1129072]","[1120224, 1120560, 1707888, 1120336, 1120112]","[1015.4285714285714, 998.1428571428571, 1111.8..."
10,2,123.551351,6169.102024,"[164.7741935483871, 160.61290322580646, 165.87...",18.525170,73.779009,167.319143,22,81,1,4.0,"[1122016, 1150128, 1134336, 1123248, 1123472]","[1120224, 1707888, 1120112, 1984864, 1120560]","[1076.7142857142858, 1134.0, 1150.285714285714..."
5,3,89.291892,4305.058227,"[116.35483870967742, 113.6774193548387, 119.67...",18.567920,73.770989,150.412799,18,65,1,2.0,"[1122016, 1134336, 1150128, 1123248, 1129072]","[1120224, 1707888, 1120560, 1120112, 1120448]","[807.2857142857143, 776.4285714285714, 773.285..."
2,4,66.437838,3394.295997,"[103.87096774193549, 89.41935483870968, 88.193...",18.556043,73.812341,168.349801,15,46,1,1.0,"[1122016, 1150128, 1134336, 1123248, 1129184]","[2026640, 1707888, 1120224, 1120560, 1984864]","[588.2857142857143, 604.2857142857143, 604.714..."
13,5,153.016216,8137.354096,"[215.67741935483872, 214.09677419354838, 210.3...",18.683466,73.731081,172.322631,27,99,1,5.0,"[1122016, 1150128, 1134336, 1123248, 1134896]","[1120224, 2026640, 1120336, 1984864, 1670032]","[1375.857142857143, 1447.5714285714287, 1467.4..."
11,6,129.740541,6526.861397,"[173.61290322580646, 190.96774193548387, 179.8...",18.665461,73.808566,166.869729,27,84,1,4.0,"[1122016, 1134336, 1150128, 1123248, 1134896]","[1707888, 1120560, 1120224, 1120112, 1120672]","[1131.2857142857142, 1178.2857142857142, 1213...."
6,7,85.345946,4308.714639,"[103.03225806451613, 115.0, 110.87096774193549...",18.565205,73.911494,157.969126,27,61,1,2.0,"[1122016, 1134336, 1150128, 1123248, 1134896]","[1120560, 1984864, 1120112, 1120224, 2026640]","[620.7142857142857, 760.8571428571429, 766.714..."
7,8,100.070270,4807.208103,"[135.29032258064515, 133.5483870967742, 136.32...",18.529224,73.860415,161.140333,22,65,1,3.0,"[1122016, 1150128, 1134336, 1123248, 1134896]","[2026640, 1120224, 1984864, 1707888, 1120112]","[829.1428571428571, 828.8571428571429, 887.0, ..."
4,9,86.135135,4298.796934,"[108.74193548387096, 117.90322580645162, 120.2...",18.435227,73.889246,178.433348,23,58,1,2.0,"[1122016, 1150128, 1134336, 1123248, 1124256]","[1120336, 1120560, 1984864, 1120112, 1120224]","[725.8571428571429, 782.4285714285714, 791.857..."
8,10,111.832432,5400.816400,"[148.5483870967742, 139.19354838709677, 147.45...",18.508610,73.934341,173.133085,25,58,1,3.0,"[1122016, 1150128, 1134336, 1123248, 1129072]","[1120224, 2026640, 1120560, 1707888, 1120112]","[951.8571428571429, 990.8571428571429, 985.428..."
3,11,72.908108,3664.071299,"[87.90322580645162, 93.03225806451613, 95.5161...",18.635565,73.843959,175.837403,24,39,1,1.0,"[1122016, 1150128, 1134336, 1123248, 1129184]","[1120224, 2026640, 1120560, 1120112, 1670032]","[609.4285714285714, 619.7142857142857, 633.714..."
1,12,53.345946,2567.325078,"[66.61290322580645, 68.2258064516129, 70.51612...",18.606168,73.874991,172.209985,27,35,1,1.0,"[1134336, 1150128, 1122016, 1123248, 1129072]","[1707888, 1120672, 1670032, 1120560, 1939280]","[474.85714285714283, 443.57142857142856, 478.2..."
0,13,11.221622,529.207441,"[15.870967741935484, 14.483870967741936, 13.16...",18.599301,73.927049,194.252731,7,7,1,1.0,"[1134336, 1122016, 1150128, 1123248, 1129072]","[1120448, 1984864, 1120672, 1120560, 1120224]","[98.42857142857143, 91.0, 82.57142857142857, 1..."

In [14]:
pods

,area,area_priority,lat,long,distance_from_ware_house,pod1,pod2,pod3,distance_from_pod_if_made,closest_pod_or_warehouse
0,0,2.666667,18.485728,73.802289,23.408588,0.000000,23.189913,20.658563,0.000000,pod1
1,2,2.636364,18.526163,73.795066,19.861086,4.540201,18.750943,16.377413,4.540201,pod1
2,5,2.629630,18.681886,73.725115,18.165195,23.189913,0.000000,10.928606,0.000000,pod2
3,6,2.481481,18.670743,73.828048,7.329557,20.658563,10.928606,0.000000,0.000000,pod3
4,3,2.388889,18.572750,73.778681,17.008054,9.949574,13.336953,12.032818,9.949574,pod1
5,1,2.269231,18.513894,73.795588,20.986450,3.196990,20.026890,17.695999,3.196990,pod1
6,4,2.266667,18.546868,73.819992,16.536195,7.020868,17.988744,13.737732,7.020868,pod1
7,8,2.181818,18.512602,73.857374,18.660788,6.533531,23.365526,17.775795,6.533531,pod1
8,10,1.960000,18.525055,73.923069,17.022023,13.476576,27.162630,18.989972,13.476576,pod1
9,9,1.913043,18.425186,73.875990,27.946355,10.271872,32.573152,27.647241,10.271872,pod1
10,7,1.629630,18.567508,73.917738,12.295152,15.183173,23.946928,14.837761,12.295152,distance_from_ware_house
11,11,1.500000,18.633523,73.847934,7.074805,17.053913,14.020210,4.623310,4.623310,pod3
12,12,1.074074,18.616141,73.876334,7.072477,16.415727,17.536427,7.904777,7.072477,distance_from_ware_house
13,13,1.000000,18.605777,73.920581,8.244049,18.235474,22.278536,12.126106,8.244049,distance_from_ware_house

### Predicting Sales of next item

In [15]:
import xgboost as xgb

In [16]:
area_df.columns

Index(['customer_id', 'manufacturer_id', 'society_id', 'city_id', 'route_id',
       'store_id', 'order_id', 'order_date', 'category_id', 'subcategory_id',
       'product_id', 'product_quantity', 'selling_price_per_unit',
       'total_cost', 'subscription', 'product_addedtobasket_on',
       'order_placed_date', 'order_placed_day', 'order_placed_month',
       'order_placed_day_of_week', 'order_placed_hour', 'order_day',
       'order_week', 'order_month', 'order_day_of_week', 'lat', 'long', 'area',
       'week_of_month'],
      dtype='object')

In [17]:
area_df = df.loc[df.area == 0]
area_df =area_df.drop(['customer_id', 'manufacturer_id', 'society_id', 'city_id', 'route_id',
       'store_id', 'order_id','total_cost','product_addedtobasket_on',
       'order_placed_date', 'order_placed_day', 'order_placed_month',
       'order_placed_day_of_week', 'order_placed_hour','lat','long','subscription','order_date'],axis=1)
area_df
# area_df.groupby(["order_date","product_id"]).mean()
product_quantity = area_df.groupby(["order_week","product_id"]).product_quantity.sum()
area_df = area_df.groupby(["order_week","product_id"]).mean()
area_df["product_quantity"] = product_quantity
area_df = area_df.reset_index()

# area_df =area_df.drop([''],axis=1)
area_df["time_value"] = area_df.index
# area_df

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import math
x = area_df.drop(["product_quantity"],axis=1)
y = area_df["product_quantity"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, shuffle=False )
xgb_reg = xgb.XGBRegressor(n_estimators=300, n_jobs=-1,max_depth=3,verbosity =0)
m=xgb_reg.fit(X_train, y_train)
pred = m.predict(X_test)

C:\Users\am21907\AppData\Local\Continuum\anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \

In [19]:
pred

array([ 8.60029793e+00,  2.63093901e+00,  3.09437084e+00,  1.02457438e+01,
        5.68120670e+00,  4.42435837e+00,  4.53997040e+00,  9.40320587e+00,
        9.52433968e+00,  1.18092642e+01,  6.63204622e+00,  5.34503651e+00,
        4.09969330e+00,  8.82573986e+00,  9.63950443e+00,  1.04537373e+01,
        1.03155041e+01,  6.49084949e+00,  3.69430995e+00,  6.64787769e+00,
        2.69584632e+00,  8.79533195e+00,  6.31782103e+00,  1.03945208e+01,
        1.21580505e+01,  2.98951149e+01,  8.71801853e+00,  1.32525053e+01,
        1.00972557e+01,  3.42421079e+00,  3.46643662e+00,  1.18066034e+01,
        3.74442577e+00,  3.97400856e+00,  4.54405499e+00,  9.67447853e+00,
        4.41643810e+00,  9.63361359e+00,  1.70796013e+01,  8.98542643e-01,
        2.83366275e+00,  1.55602062e+00,  8.47513657e+01,  3.19188652e+01,
        1.36631775e+00,  1.36631775e+00,  2.36292458e+00,  5.68717766e+00,
        2.03625417e+00,  2.63667417e+00,  2.65036178e+00,  2.03625417e+00,
        5.66496515e+00,  3.39737701e+00,  1.74599648e+00,  3.28729105e+00,
        3.31151319e+00,  1.36059999e+00,  3.25356865e+00,  2.28278303e+00,
        1.92542064e+00,  2.92395449e+00,  1.67010868e+00,  1.79810381e+00,
        4.30237627e+00,  3.63888550e+00,  1.09277225e+00,  1.11349440e+00,
        2.64022231e+00,  1.02863324e+00,  8.29641724e+00,  1.36059999e+00,
        9.94384766e+00,  1.45980167e+01,  8.71491051e+00,  1.54455197e+00,
        2.45921135e+00,  3.37786031e+00,  2.01598978e+00,  7.60666990e+00,
        5.59086561e+00,  6.84609270e+00,  3.41994572e+00,  2.79908299e+00,
        3.03990245e+00,  3.25277257e+00,  3.35537720e+00,  1.03975391e+00,
        3.25277257e+00,  3.25277257e+00,  1.45116925e+00,  3.00003204e+01,
        3.84223676e+00,  3.00676847e+00,  4.05667448e+00,  4.20014095e+00,
        1.71780145e+00,  3.15972304e+00,  3.04430461e+00,  3.90637636e+00,
        1.22236423e+01,  1.41450620e+00,  3.74105883e+00,  6.67797089e-01,
        3.31771445e+00,  4.40034065e+01,  4.13836432e+00,  3.31077170e+00,
        4.28263950e+00,  5.23394775e+00,  4.71421385e+00,  4.71421385e+00,
        4.79411888e+00,  1.25603798e+02,  1.47509408e+00,  1.75130689e+00,
        9.62160587e+00,  3.27497911e+00,  8.40661287e-01,  1.49876690e+00,
        2.01424313e+00,  1.55318797e+00,  7.76201844e-01,  1.76735723e+00,
        3.93826270e+00,  4.16331196e+00,  1.56129134e+00, -2.45676136e+00,
        9.41480517e-01,  3.22512960e+00,  1.79771125e+00,  1.68806100e+00,
        1.52060580e+00,  4.92415762e+00,  9.26195812e+00,  1.56150331e+01,
        3.44380035e+01,  9.18525696e+00,  5.30456400e+00,  1.43899784e+01,
        3.41412115e+00,  5.79823112e+00,  1.53146763e+01,  3.54013348e+00,
        1.82808518e+00,  1.31291330e+00,  5.07485926e-01,  3.25966620e+00,
        3.25966620e+00,  4.18107224e+00,  1.42925227e+00,  3.61704540e+00,
        1.87645340e+01,  2.76902657e+01,  7.53998101e-01,  1.15391850e+00,
        4.16079140e+00,  1.73607850e+00,  4.47762203e+00,  3.02367163e+00,
        2.82176971e+00,  2.94714379e+00,  8.73847294e+00,  6.26070738e-01,
        1.68692350e+00,  2.09393454e+00,  2.38279152e+00,  2.38279152e+00,
        1.33965850e+00,  1.76585217e+01,  2.74938297e+00,  2.74938297e+00,
        8.62371564e-01,  1.37215531e+00,  5.02092791e+00,  3.00168562e+00,
        3.12266493e+00,  3.08028936e+00,  1.12756701e+01,  1.08648968e+00,
        9.46606994e-01,  1.82463474e+01,  3.26417136e+00,  4.15306377e+00,
        2.88427520e+00,  6.45199776e+00,  4.96931696e+00,  2.78511333e+01,
        2.90935874e+00,  1.27669048e+00,  2.16558290e+00,  1.87784576e+00,
        1.16286278e+00,  2.42768550e+00,  1.23589087e+00,  1.45448017e+01,
        3.57070851e+00,  3.01024342e+00,  4.52497768e+00,  8.95787179e-01,
        2.26744699e+00,  1.41597235e+00,  2.69676089e+00,  1.43582261e+00,
        2.20333982e+00,  3.05279660e+00,  2.03885221e+00,  3.09380579e+00,
        3.73261857e+00,  2.72671342e+00,  3.47300410e+00,  1.36542034e+00,
        8.17079425e-01,  3.81273103e+00,  3.49849916e+00,  2.31861496e+00,
        9.62403059e-01,  1.87904418e+00,  1.12424660e+00,  5.65419769e+00,
        1.41685081e+00,  1.13232708e+00,  9.90491104e+00,  2.23493147e+00,
        2.23493147e+00,  2.90885186e+00,  8.53812695e-01,  2.23039341e+00,
        2.00089240e+00,  1.90537691e+00,  2.57463527e+00,  2.90428782e+00,
        2.05806255e+00,  2.94695711e+00,  9.62403059e-01,  7.16441572e-01,
        1.56175089e+00,  1.37741530e+00,  2.99176908e+00,  4.61289549e+00,
        2.24631500e+01,  2.78272986e+00,  4.07172585e+00,  2.46895266e+00,
        2.99176908e+00,  3.02115726e+00,  6.27550316e+00,  2.29570055e+00,
        2.19686794e+00,  1.97856843e+00,  9.78018093e+00,  1.94651783e+00,
        1.94651783e+00,  1.03559446e+00,  3.71213645e-01,  7.88166761e-01,
       -4.27419782e-01,  6.13662064e-01,  7.53955317e+00,  5.21853304e+00,
        6.07004166e+00,  8.83779883e-01,  2.17173815e+00,  8.53211522e-01,
        1.79618537e+00,  8.05375099e-01,  8.05375099e-01,  8.05375099e-01,
        1.46788239e+00,  7.91971564e-01,  3.33355212e+00,  1.10126901e+00,
        7.90305674e-01,  4.04916286e+00,  1.22397101e+00,  3.24220276e+00,
        1.44379950e+00,  3.24633694e+00,  9.17129993e-01,  1.19072890e+00,
        2.41961718e+00,  2.32446432e+00,  4.04916286e+00,  4.11203384e+00,
        2.08670712e+00,  8.24340105e-01,  1.77712053e-01,  1.46282434e+00,
        1.41683054e+00,  1.34329545e+00,  1.12210143e+00,  3.09380579e+00,
        1.26607113e+01,  9.30562317e-02,  3.19810677e+00,  7.15522385e+00,
        3.59569073e+00,  1.61450851e+00,  9.26399112e-01,  1.04979920e+00,
        1.05699849e+00,  3.02648604e-01,  3.22320938e+00,  3.04916286e+00,
        1.50041640e+00,  8.46499205e-01,  1.06271625e+00,  1.06271625e+00,
        7.42868662e-01,  7.42868662e-01,  1.06271625e+00, -3.70277286e-01,
        4.26559877e+00,  4.10636330e+00,  3.27547646e+00,  2.79290915e+00,
        6.21377051e-01,  3.22352052e+00,  1.29185343e+00,  1.06271625e+00,
        6.21377051e-01,  1.06271625e+00,  4.51317120e+00,  4.59636545e+00,
        1.11535845e+01,  5.36777782e+00,  6.09443188e+00,  5.36777782e+00,
        5.41973114e+00,  9.05282974e+00,  9.09412918e+01,  1.25130356e+02,
        8.29636841e+01,  7.04557419e+01,  1.31975952e+02,  2.59203529e+01,
        1.03343906e+01,  3.71140480e+00,  1.70737648e+01,  5.20950890e+00,
        5.78981733e+00,  9.36386406e-01,  4.37305510e-01,  1.69321740e+00,
        6.52110863e+00,  1.11921859e+00,  9.81040859e+00,  1.19884109e+00,
        9.60536659e-01,  9.60536659e-01,  9.54818845e-01,  9.15918350e+00,
        4.20845413e+00,  3.37893510e+00,  1.26087952e+00,  1.03608930e+00,
        3.12049150e+00,  3.80056596e+00,  3.24504495e+00,  2.18689299e+00,
        7.24450493e+00,  1.04960537e+00,  8.08708608e-01,  8.62106681e-01,
        1.39145079e+01,  8.39058113e+00,  1.43443131e+00,  2.08760762e+00,
        3.32666445e+00,  3.18107963e+00,  3.81385207e+00,  2.88250351e+00,
        3.91335440e+00,  1.33562350e+00,  5.66752529e+00,  3.10700107e+00,
        1.21192586e+00,  1.42371321e+00,  5.35852671e+00,  3.30649543e+00,
        1.24031234e+00,  1.24031234e+00,  2.04496694e+00,  1.33562350e+00,
        1.33562350e+00,  2.20007467e+00,  2.48781443e+00,  9.32381034e-01,
        9.32381034e-01,  1.35697985e+00,  9.32381034e-01,  1.88668013e+00,
        9.32381034e-01,  8.53557944e-01,  3.08386397e+00,  5.03842640e+00,
        4.17245054e+00,  5.67652321e+00,  3.15442872e+00,  3.50099015e+00,
        3.22339892e+00,  3.18610358e+00,  3.10968137e+00,  3.10968137e+00,
        3.18610358e+00,  4.21476984e+00,  3.14932036e+00,  8.16814232e+00,
        2.97621226e+00,  1.35909438e+00,  2.84476352e+00,  3.45372462e+00,
        3.74162459e+00,  1.07012594e+00,  1.60299325e+00,  5.25029063e-01,
        1.02255034e+00,  7.10562170e-01,  5.71884251e+00,  4.75005817e+00,
        1.86224329e+00,  1.62805068e+00,  6.16316438e-01,  7.61827898e+00,
        1.13925767e+00,  8.07946968e+00,  9.35835361e-01,  1.85027957e+00,
        4.59309721e+00,  8.15524101e+00,  1.83911908e+00,  1.06010628e+00,
        1.82114494e+00,  1.82114494e+00,  4.20526218e+00,  2.17155409e+00,
        2.42350817e+00,  2.13603573e+01,  3.25977554e+01,  8.09976864e+00,
        1.34839010e+00,  2.77466226e+00,  2.35913420e+00,  1.89730847e+00,
        2.77146549e+01,  1.52918160e+00,  1.21633601e+00,  1.11050415e+01,
        1.25192511e+00,  3.95857692e+00,  1.00669594e+01,  1.67290249e+01,
        2.19634933e+01,  2.05911694e+01,  1.47818270e+01,  4.85595560e+00,
        4.72180557e+00,  1.04968853e+01,  6.78165340e+00,  1.09953432e+01,
        1.21116352e+01,  3.85485220e+00,  6.58016014e+00,  3.46398020e+00,
        3.31547141e+00,  3.31547141e+00,  5.85486603e+00,  3.31547141e+00,
        5.52729559e+00,  4.17624235e+00,  2.36553364e+01,  4.57951069e+00,
        1.66736088e+01,  6.04347372e+00,  1.09634228e+01,  9.31175900e+00,
        7.77423024e-01,  2.91294403e+01,  1.23371420e+01,  3.16382813e+00,
        4.17457294e+00,  2.96118855e+00,  9.44557095e+00,  4.85161018e+00,
        1.29188852e+01,  8.53771057e+01,  2.77973404e+01,  8.63094044e+00,
        8.90062451e-01,  1.02334166e+00,  1.45973110e+00,  1.38053644e+00,
        2.25030637e+00,  1.51482189e+00,  1.57508481e+00,  1.52889824e+00,
        2.44855452e+00,  1.31625736e+00,  1.31625736e+00,  2.00432968e+00,
        1.17289031e+00,  6.99100614e-01,  4.88374949e+00,  1.27851763e+01,
        1.84800839e+00,  2.18651390e+00,  1.81985319e+00,  2.39159918e+00,
        8.66747737e-01,  8.66747737e-01,  1.36189489e+01,  3.82496023e+00,
        1.34729605e+01,  4.67020512e+00,  7.89669633e-01,  3.83560729e+00,
        3.78353953e+00,  3.83560729e+00,  7.02272987e+00,  1.01119208e+00,
        1.95865953e+00,  2.86900349e+01,  2.83914852e+00,  4.71836424e+00,
        2.82742476e+00,  1.35606945e+00,  1.08259172e+01,  4.16361618e+00,
        4.85669076e-01,  1.92546952e+00,  5.03123283e+01,  2.70818043e+00,
        5.21218729e+00,  1.30785599e+02,  2.69039965e+00,  2.56284885e+01,
        1.54175282e+00,  4.93949032e+00,  2.29043818e+00,  9.58657455e+00,
        9.58964944e-01,  2.63743997e+00,  3.59125304e+00,  3.96863484e+00,
        7.37973034e-01,  2.49111724e+00,  3.04716140e-01,  4.99415725e-01,
        2.38395786e+00,  3.06976962e+00,  5.02356482e+00,  4.33121777e+00,
        1.08869982e+01,  4.40016251e+01,  5.98339748e+00,  6.18080091e+00,
        1.08564055e+00,  8.11313725e+00,  1.22475028e+00,  3.15165591e+00,
        3.08485937e+00,  1.46732664e+01,  2.50658607e+01,  3.61814380e+00,
        5.26998663e+00,  3.89451599e+00,  2.19331884e+00,  1.47374082e+00,
        3.18604851e+00,  5.34755707e-01,  1.15627766e+00,  1.42262030e+00,
        3.76903582e+00,  1.18096745e+00,  1.05660701e+00,  1.64378052e+01,
        3.30801105e+00,  9.76635575e-01,  9.36983824e-01,  4.38248062e+00,
        3.28426647e+00,  5.47627020e+00,  2.20500393e+01,  3.27792215e+00,
        7.60245562e-01,  7.81885982e-01,  1.69074833e+00,  1.37962270e+00,
        1.26574898e+00,  2.72865725e+00,  7.87776828e-01,  1.13800836e+00,
        1.16302919e+00,  3.82758200e-01,  2.53391480e+00,  1.76535952e+00,
        8.19642901e-01,  9.53917694e+00,  3.21035123e+00,  4.69644880e+00,
        6.17880166e-01,  3.26145697e+00,  3.08257389e+00,  1.22257004e+01,
        1.16118968e+00,  1.59091735e+00,  1.22444212e+00,  1.81459844e+00,
        9.98128057e-01,  4.85083103e+00,  5.96357775e+00,  1.26003122e+00,
        1.26828394e+01,  5.93160057e+00,  1.27422404e+00,  1.47006679e+00,
        1.26003122e+00,  1.85660839e+00,  1.42663503e+00,  9.07148600e-01,
        9.07148600e-01,  1.16031706e+00,  4.21482944e+00,  1.09256947e+00,
        1.57435207e+01,  1.04234266e+00,  1.85698581e+00,  1.29461122e+00,
        1.08552313e+00,  1.25420523e+00,  6.00282073e-01,  6.75343812e-01,
        1.10043585e-02,  1.20334187e+01,  7.65577316e-01,  1.07049131e+00,
        7.05796385e+00,  6.71564484e+00,  9.95612800e-01,  1.71412933e+00,
        9.55960870e-01,  3.24267721e+00,  2.78413606e+00,  2.78413606e+00,
        1.44159746e+00,  5.03716135e+00,  1.20264006e+00,  1.07049131e+00,
        8.84170651e-01,  4.58084393e+00,  1.03222418e+00,  3.51029778e+00,
        1.24125171e+00,  1.21620011e+00,  1.21620011e+00,  1.48880255e+00,
        1.48880255e+00,  1.98437333e+00,  1.35118496e+00,  1.24125171e+00,
        3.32004714e+00,  2.78092313e+00,  1.86960888e+00, -1.34541214e-01,
        2.57246518e+00,  1.95676804e+00,  3.97263408e+00,  3.08122826e+00,
        1.69367752e+01,  1.05355215e+00,  6.43236399e+00,  2.92949891e+00,
        6.73019409e-01,  8.93434763e-01,  8.45618248e-01,  5.64414787e+00,
        1.13090873e+00,  2.82509422e+00,  1.03588247e+00,  5.95807314e-01,
        8.54562569e+00,  4.70431423e+00, -1.08917367e+00, -1.48756027e+00,
       -1.01031005e+00,  1.54647207e+00,  3.87799716e+00,  5.47721291e+00,
        6.65723228e+00,  7.06224394e+00,  6.98879671e+00,  6.96180115e+01,
        1.01008080e+02,  6.19665489e+01,  5.64037247e+01,  1.19159805e+02,
        2.16003265e+01,  1.69424939e+00,  1.56353486e+00,  2.11233997e+00,
        1.07648253e+00,  9.30839777e-01,  1.34483743e+00,  1.83234262e+00,
        2.30183506e+00,  2.86683369e+00,  1.63954890e+00,  3.21379161e+00,
        8.87017012e-01,  4.08274555e+00,  3.33962321e+00,  1.74765265e+00,
        9.00632083e-01,  8.48948300e-01,  7.62029290e-01,  3.94045091e+00,
        7.36941004e+00,  9.93767679e-01,  1.66862893e+00,  1.13099146e+00,
        2.14652205e+00,  2.55912876e+00,  6.17572737e+00,  2.47997284e+00,
        3.71312380e+00,  1.42500782e+00,  1.42500782e+00,  3.81939828e-01,
        6.80515409e-01,  1.17891538e+00,  1.57479000e+00,  3.28068161e+00,
        3.01306105e+00,  7.84416199e-01,  1.62945199e+00,  4.24732804e-01,
        7.57749319e-01,  4.73050880e+00,  9.49148774e-01,  8.39435768e+00,
        3.21106458e+00,  2.62873974e+01,  1.20509315e+00,  9.41707492e-01,
        1.20932877e+00,  9.41707492e-01,  1.76490259e+00,  1.83958077e+00,
        5.23365068e+00,  4.45069838e+00,  6.04804754e+00,  6.47183466e+00,
        7.32135248e+00,  4.21419048e+00,  4.92892647e+00,  4.67278385e+00,
        5.00419331e+00,  4.75011110e+00,  3.56220579e+00,  5.98364305e+00,
        3.66134930e+00,  6.17925787e+00,  4.04667521e+00,  5.09585333e+00,
        1.74506664e+01,  5.22215891e+00,  5.94909430e+00,  4.86928606e+00,
        1.47696781e+00,  3.89622903e+00,  3.42316461e+00,  2.84626937e+00,
        3.50869870e+00,  1.23122530e+01,  6.01290822e-01,  7.65407562e+01,
        1.66254063e+01,  2.81006074e+00,  2.96061563e+00,  1.27672648e+00,
        8.25943708e-01,  2.81006074e+00,  1.27370882e+00,  8.25943708e-01,
        9.42761838e-01,  8.25943708e-01, -1.27275229e-01,  1.20890737e+00,
        2.97043180e+00,  1.28244424e+00,  1.23467350e+00,  1.36982393e+00,
        2.49827290e+00,  1.36982393e+00,  1.04151564e+01,  3.96919608e+00,
        1.41390300e+00,  3.65926909e+00,  3.97098827e+00,  1.67861319e+00,
        2.02816582e+01,  3.63262701e+00,  1.01858926e+00,  3.34185743e+00,
        3.78022170e+00,  3.00270653e+00,  4.92095375e+00, -7.71695495e-01,
       -1.80634320e-01,  3.14184213e+00,  3.52101746e+01,  1.16592537e+02,
        2.29783869e+00,  2.78090239e+00,  1.74838662e+00,  3.98956800e+00,
        3.21235895e+00,  6.21002495e-01,  3.98353910e+00,  3.15223551e+00,
        7.82431662e-01,  1.52369034e+00,  1.55506480e+00,  5.36647320e-01,
        3.05902767e+00,  4.15286112e+00,  2.84884434e+01,  5.47915459e+00,
        1.27378702e+00, -1.85463428e-02,  3.48846412e+00,  3.29677963e+00,
        4.86705828e+00,  1.20753765e+01,  4.93278790e+00,  3.23762870e+00,
        3.34552836e+00,  2.29573679e+00,  7.08103776e-01,  8.32369208e-01,
        7.08103776e-01,  1.40883791e+00,  1.40822363e+00,  7.31491208e-01,
        3.07790780e+00,  3.07790780e+00,  1.70119190e+01,  1.63924408e+00,
        2.86699510e+00,  2.07541227e+00,  1.18196714e+00,  1.24475279e+01,
        3.00053740e+00,  7.37209022e-01,  2.48324347e+00,  3.10530519e+00,
        2.29573679e+00,  6.31951690e-01,  1.31467152e+00,  1.17038226e+00,
        7.74965763e-01,  2.11316919e+00,  1.42478514e+00,  6.52434349e-01,
        7.69248009e-01,  1.44559932e+00,  7.74965763e-01,  5.42494631e+00,
        1.17610002e+00,  8.62553120e-01,  1.44372129e+00,  7.69248009e-01,
        1.81719542e+00,  3.51742697e+00,  2.34510756e+00,  6.31209493e-01,
        1.90712795e+01,  1.12085533e+00,  7.33291686e-01,  1.00041962e+00,
        2.49187708e+00,  7.33291686e-01,  1.45828497e+00,  3.87250471e+00,
        1.02111554e+00,  7.32798755e-01,  3.36450553e+00,  4.14012527e+00,
        3.38746333e+00,  6.45931005e+00,  1.02989972e+00,  6.22455716e-01,
        6.16737962e-01,  3.16104198e+00,  6.40125394e-01,  6.45843208e-01,
       -2.26804733e+00,  5.26354790e+00,  3.42852068e+00,  8.90076578e-01,
        6.22455716e-01,  3.42852068e+00,  3.42852068e+00,  3.45234060e+00,
        5.59659719e+00,  5.30515671e+00,  4.02653933e+00,  5.57277822e+00],
      dtype=float32)

In [20]:
math.sqrt(mean_squared_error(y_test, pred))

6.679973067369531

In [21]:
predictions = []
for index,row in area_insights.iterrows():
    preds = []
    for product in row.top_5_products:
        temp=x.loc[x.product_id==product].iloc[0,:]
        next_ = {"product_id" : temp.product_id,"category_id":temp.category_id,"subcategory_id":temp.subcategory_id,"selling_price_per_unit":temp.selling_price_per_unit,"order_day":1.0,"order_week":32.0,"order_month":8.0,"order_day_of_week":3.0,"week_of_month":1.0,"time_value":764233.0} 
        next_ = pd.DataFrame([next_])
        t = pd.DataFrame(columns=x.columns)
        t.loc[0]=next_.iloc[0,:]
        preds.append(m.predict(t)[0])
    predictions.append(preds)
area_insights["estimated_quantity_of_sale"] = predictions

In [23]:
area_insights.to_csv("../output/area_insights_without_recomendations.csv",index=None)
area_insights
pods.to_csv("../output/pod_data.csv",index=None)